work_dir: './work_dir/prediction'
weights: '<the dir of saved model.pt ...>'
train_dir: '../data/cmu/train'
test_dir: '../data/cmu/test'

actions: 'all'
batch_size: 32
source_seq_len: 50
target_seq_len: 10

model: net.model.Model
model_args:
  n_in_enc: 3
  n_hid_enc: 256
  n_in_dec: 9
  n_hid_dec: 256
  fusion_layer: 2
  cross_w: 0.3
  graph_args_j:
    layout: 'cmu'
    strategy: 'distance'
  graph_args_p:
    layout: 'cmu'
    strategy: 'distance'
  graph_args_b:
    layout: 'cmu'
    strategy: 'distance'
edge_weighting: True
lamda: 0.6
 
phase: test
device: [0]
use_gpu: True

fusion_layer_dir: test
learning_rate_dir: test
lamda_dir: test
crossw_dir: test
note: test